version: '{build}'

image: Visual Studio 2017

environment:
  BOOST_ROOT: C:/Libraries/boost_1_67_0
  matrix:
    - GENERATOR: "Visual Studio 15 Win64"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -Bbuild
  - cmake --build build --config "%CONFIG%"

artifacts:
    - path: build/bin
      name: binary
      type: zip

deploy:
    provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
        secure: xrpz/h0MgyGQnKb+KFm3Nqx5y0Uu3OIFr3tszZ7OKj676lx8mofty+jVWH53gUgh
    force_update: true
    on:
        branch: master
        appveyor_repo_tag: true


